"""Update UserLike to track action type

Revision ID: 4391104736d2
Revises: a8d21c71fed4
Create Date: 2025-08-26 13:49:05.742149

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4391104736d2'
down_revision = 'a8d21c71fed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the new columns as nullable
    op.add_column('user_likes', sa.Column('action', sa.String(), nullable=True))
    op.add_column('user_likes', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Update existing records to have 'like' action (since they were all likes before)
    op.execute("UPDATE user_likes SET action = 'like' WHERE action IS NULL")
    
    # Now make action column not nullable
    op.alter_column('user_likes', 'action', nullable=False)
    
    # Drop the old column
    op.drop_column('user_likes', 'liked_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_likes', sa.Column('liked_at', sa.DateTime(), nullable=True))
    op.drop_column('user_likes', 'created_at')
    op.drop_column('user_likes', 'action')
    # ### end Alembic commands ###
